### ISSUE TITLE
Decrypt password for windows dont work

### ISSUE THREAD

**Issue by grildev** [phoqe/havelock#107]

**Comment by grildev** [comment]
Decrypt function for win32 dont work because dont return nothing [Here](https://github.com/phoqe/havelock/blob/develop/crypto/win32.js#L72)

**Comment by phoqe** [comment]
Yes, that is correct. The Windows decrypt function is yet to be implemented, there's only a stub implementation to prevent exceptions. I don't have a Windows machine at the moment.

**Comment by phoqe** [comment]
#9
