### ISSUE TITLE
Any support for windows yet?

### ISSUE THREAD

**Issue by loganblackk** [phoqe/havelock#11]
I've been frantically looking for a way to export my brave history since there's no official way. I've gone down just about every alley and utility for windows, and am calling it quits at this point. I  hoped this would be the fix but no dice.

**Comment by phoqe** [comment]
Hello Logan, I am sorry to inform you that I haven't had the time to add support for Windows yet. I do, however, have a tool exclusively for Windows made in C#. If you want I can share access to the repository with you? Thank you for your interest :)

**Comment by phoqe** [comment]
@loganblackk

**Comment by loganblackk** [comment]
This tool is the same thing but for windows in c#?

**Comment by phoqe** [comment]
@loganblackk It has the same capabilities, but it is not the same underlying API.

**Comment by phoqe** [comment]
I may have misread your inquiry, do you only want the history associated with Brave? No string decryption? If so, there is support for Windows available in Havelock. The only thing that is macOS only is string decryption so far.

You can use Havelock like this:
```js
const havelock = require("havelock");

const explorer = havelock.explorer;
const browser = havelock.browser;

explorer
  .getDataFromUserDataDirectoryFile(
    browser.brave,
    "Default",
    "History",
    "urls"
  )
  .then(value => {
    console.log(value);
  })
  .catch(reason => {
    console.error(reason);
  });
```

Reach back to me if you have any questions.

**Comment by phoqe** [comment]
I'm closing this, for now, feel free to reopen.
