### ISSUE TITLE
Improve API for beginners

### ISSUE THREAD

**Issue by phoqe** [phoqe/havelock#7]
The API might feel a bit unnatural at the moment, why don’t we make it more JS-esque?

**Comment by its-tayo** [comment]
Hi @phoqe can I have a go at this?

**Comment by phoqe** [comment]
@its-tayo Yes! You are very welcome to.

**Comment by its-tayo** [comment]
@phoqe Right! I'll look at the codebase today, can you please add some more details to this so I understand what needs to be done?

> The API might feel a bit unnatural at the moment, why don’t we make it more JS-esque?

**Comment by phoqe** [comment]
Hmm, the API might feel a bit "new" and "unfamiliar" when accustomed to other Node libraries. I don't know if it's just me. What do you think?
